reown-com/web-examples

- README.md
- Change V2 to v2
- Bolding v2
- Add `:` after name
- change readme to README
> A bit update on WalletConnect v2 Examples/MD

- dapps/react-dapp-v2/package.json
- dapps/react-dapp-v2/src/contexts/ClientContext.tsx
- dapps/react-dapp-v2/yarn.lock
https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.0.0-beta.102
> chore(deps): upgrade dapp to beta.102

- dapps/react-dapp-v2/src/constants/default.ts
- Change `process.env.RELAY_URL` to `process.env.NEXT_PUBLIC_RELAY_URL`
> Fix incorrect env var ref

- dapps/react-dapp-auth/pages/index.tsx
- wallets/react-wallet-auth/src/components/Navigation.tsx
- Removed sessions from nav as the concept doesn't exist in auth
> Remove session from nav for auth

- dapps/react-dapp-auth/pages/index.tsx
> Fix add projectid

- dapps/react-dapp-auth/package-lock.json
- dapps/react-dapp-auth/package.json
- dapps/react-dapp-auth/pages/index.tsx
- use auth 0.1.10
- pass full chainId
> Updated dapp

- wallets/react-wallet-v2/src/utils/WalletConnectUtil.ts
fix name NEXT_PUBLIC_RELAY_URL
> fix(wallet): NEXT_PUBLIC_RELAY_URL reference

- dapps/react-dapp-auth/package-lock.json
- dapps/react-dapp-auth/package.json
- dapps/vue-dapp-auth/package.json
- dapps/vue-dapp-auth/yarn.lock
- wallets/react-wallet-auth/package-lock.json
- wallets/react-wallet-auth/package.json
- wallets/react-wallet-auth/src/hooks/useInitialization.ts
- wallets/react-wallet-auth/src/utils/WalletConnectUtil.ts
- wallets/react-wallet-auth/src/views/AuthenticationRequestModal.tsx
Updated `Auth Wallet` example to the latest auth version
> feat: auth wallet multi address

- wallets/react-web3wallet/README.md
updated the web3wallet readme to fix the `metadata` usage
> refactor: web3wallet readme

- dapps/react-dapp-v2/src/components/Header.tsx
- dapps/react-dapp-v2/src/pages/index.tsx
> Add Emit Function

- wallets/react-wallet-v2/src/pages/session.tsx
- wallets/react-wallet-v2/src/views/SessionProposalModal.tsx
Fixed a reported issue where in the approved namespaces, `chains` prop was missing
> fix:  chains in approved namespaces

- dapps/react-dapp-auth/pages/index.tsx
- dapps/react-dapp-auth/views/SignedInView.tsx
- wallets/react-wallet-auth/src/views/AuthenticationRequestModal.tsx
- Close web3modal if user rejects auth request
- Fix bigNumber overflow error
> fix(error-handling): close modal on reject and fix overflow error 

- wallets/react-wallet-v2/src/views/SessionProposalModal.tsx
Implemented optional namespaces for non evm namespaces
> fix: implements optional namespaces for non evm chains

- wallets/react-web3wallet/package.json
> chore: update toe latest 1.8.2

- dapps/react-dapp-v2/package.json
- dapps/react-dapp-v2/src/constants/default.ts
- dapps/react-dapp-v2/src/contexts/JsonRpcContext.tsx
- dapps/react-dapp-v2/src/pages/index.tsx
- dapps/react-dapp-v2/yarn.lock
DO NOT MERGE
This PR was made to showcase usability with wallets for `eth_signTypedData_v4`
> feat(dapp-v2): adds eth_signTypedData_v4

- dapps/react-dapp-v2/package.json
- dapps/react-dapp-v2/src/contexts/JsonRpcContext.tsx
- dapps/react-dapp-v2/yarn.lock
- wallets/react-wallet-v2/package.json
- wallets/react-wallet-v2/src/lib/MultiversxLib.ts
- wallets/react-wallet-v2/src/utils/MultiversxRequestHandlerUtil.ts
- wallets/react-wallet-v2/yarn.lock
- wallets/react-web3wallet/package.json
- wallets/react-web3wallet/src/lib/MultiversxLib.ts
- wallets/react-web3wallet/src/utils/MultiversxRequestHandlerUtil.ts
- wallets/react-web3wallet/yarn.lock
Changelist:
`react-dapp-v2`, `react-wallet-v2` & `react-web3wallet`
Updated the `@multiversx/sdk-core` library to the latest major version `12.8.0` and updated the code to implement those changes
---
You can check out the changes here:
**Wallet:**
[React Wallet (Sign v1 + v2) ](https://wc2-wallet.vercel.app/)
**dApp:**
[React dApp (with standalone client) - v2](https://wc2-dapp.vercel.app/)
> Updated the @multiversx/sdk-core library to the latest major version

- wallets/react-wallet-v2/src/pages/session.tsx
> feat: show session expiry datetime instead of just the date

- advanced/dapps/react-dapp-v2/src/contexts/ClientContext.tsx
- advanced/dapps/react-dapp-v2/src/modals/LoaderModal.tsx
- advanced/dapps/react-dapp-v2/src/modals/PairingModal.tsx
- advanced/dapps/react-dapp-v2/src/pages/index.tsx
- advanced/wallets/react-wallet-v2/src/components/Modal.tsx
- advanced/wallets/react-wallet-v2/src/components/ModalFooter.tsx
- advanced/wallets/react-wallet-v2/src/components/SessionChainCard.tsx
- advanced/wallets/react-wallet-v2/src/pages/session.tsx
- advanced/wallets/react-wallet-v2/src/pages/walletconnect.tsx
- advanced/wallets/react-wallet-v2/src/views/AuthRequestModal.tsx
- advanced/wallets/react-wallet-v2/src/views/RequestModal.tsx
- advanced/wallets/react-wallet-v2/src/views/SessionProposalModal.tsx
- advanced/wallets/react-wallet-v2/src/views/SessionSendTransactionModal.tsx
- advanced/wallets/react-wallet-v2/src/views/SessionSignCosmosModal.tsx
- advanced/wallets/react-wallet-v2/src/views/SessionSignKadenaModal.tsx
- advanced/wallets/react-wallet-v2/src/views/SessionSignModal.tsx
- advanced/wallets/react-wallet-v2/src/views/SessionSignMultiversxModal.tsx
- advanced/wallets/react-wallet-v2/src/views/SessionSignNearModal.tsx
- advanced/wallets/react-wallet-v2/src/views/SessionSignPolkadotModal.tsx
- advanced/wallets/react-wallet-v2/src/views/SessionSignSolanaModal.tsx
- advanced/wallets/react-wallet-v2/src/views/SessionSignTezosModal.tsx
- advanced/wallets/react-wallet-v2/src/views/SessionSignTronModal.tsx
- advanced/wallets/react-wallet-v2/src/views/SessionSignTypedDataModal.tsx
- advanced/wallets/react-wallet-v2/src/views/TheatPrompt.tsx
- Added loading indicators in main wallet example on all awaits
- Added loading indicators/modals in main dapp example on disconnect & proposing session on known pairing
- General house keeping - removing unused code/unused imports
> feat: loading indicators

- .github/workflows/pr_checks.yml
runs the web3modal tests exercising the sample wallet as part of every PR.
blocked on https://github.com/WalletConnect/web3modal/pull/1733/files
> feat(tests): run tests

- advanced/wallets/react-wallet-v2/src/components/SmartAccountCard.tsx
- advanced/wallets/react-wallet-v2/src/hooks/useSmartAccount.ts
Added toast message on smart account creation. Also tiny loading icon modification for alignment.
> better error messaging on smart account creation

- .github/workflows/pr_checks.yml
> fix(tests): variable not defined

- advanced/wallets/react-wallet-v2/src/pages/settings.tsx
- advanced/wallets/react-wallet-v2/src/store/SettingsStore.ts
- advanced/wallets/react-wallet-v2/src/views/SessionProposalModal.tsx
Change the order of accounts inside namespace, making smart account last instead of first
> fix: smart account feature flag

- dapps/web3modal/next/src/app/page.tsx
- dapps/web3modal/next/src/components/Contracts.tsx
- dapps/web3modal/next/src/config/index.ts
- dapps/web3modal/react/src/configs/index.ts
- dapps/web3modal/react/src/contract.tsx
- dapps/web3modal/react/src/main.tsx
> add wagmi/view 2.x

- .github/workflows/pr_checks.yml
Building lab locally in order to provide react wallet url required for deeplinks in tests
> chore: build lab locally in tests

- advanced/wallets/react-wallet-v2/src/pages/index.tsx
- advanced/wallets/react-wallet-v2/src/store/SettingsStore.ts
Display smart accounts from the list of available accounts.
Fix the settings key for safe
> fix: smart account display

- advanced/wallets/react-wallet-v2/src/components/ChainSmartAddressMini.tsx
- advanced/wallets/react-wallet-v2/src/hooks/usePriorityAccounts.ts
- advanced/wallets/react-wallet-v2/src/hooks/useSmartAccounts.ts
- advanced/wallets/react-wallet-v2/src/lib/smart-accounts/BiconomySmartAccountLib.ts
- advanced/wallets/react-wallet-v2/src/pages/settings.tsx
- advanced/wallets/react-wallet-v2/src/store/SettingsStore.ts
- advanced/wallets/react-wallet-v2/src/utils/SmartAccountUtil.ts
- advanced/wallets/react-wallet-v2/src/views/SessionProposalModal.tsx
Use Permissionless to add Biconomy V2 implementation based on SmartAccountLib
> Feat: Add Biconomy smart account

- advanced/dapps/react-dapp-v2/src/pages/index.tsx
Fixed bug where approved methods that are not supported by react dapp resulted in an unhandled exception due to undefined actions
> fix: undefined actions

- advanced/dapps/react-dapp-v2/.eslintrc.json
- advanced/dapps/react-dapp-v2/package.json
- advanced/dapps/react-dapp-v2/yarn.lock
- advanced/wallets/react-wallet-v2/.eslintrc.json
- advanced/wallets/react-wallet-v2/package.json
- advanced/wallets/react-wallet-v2/yarn.lock
Add `eslint-plugin-package-json` to the eslint plugins
> chore: add eslint package json

- advanced/wallets/react-wallet-v2/src/lib/smart-accounts/KernelSmartAccountLib.ts
changed the value parameter type from bigInt to Hex since we receive the value as a hex string
added handling of undefined data param.
> fix: kernel sendTransaction param type 

- dapps/web3modal/react/package.json
- dapps/web3modal/react/pnpm-lock.yaml
- dapps/web3modal/react/src/main.tsx
- dapps/web3modal/react/src/styles.css
+ Add social connectors
+ Style to center the button
+ Update packages to the latest version
> Feat: Add social connectors to react

- advanced/wallets/react-wallet-v2/src/lib/smart-accounts/SafeSmartAccountLib.ts
Fixing the module installation check so that it installs all the required module before granting permissions
> fix: permissions module installation

- advanced/wallets/react-wallet-v2/package.json
- advanced/wallets/react-wallet-v2/src/lib/smart-accounts/SmartAccountLib.ts
- advanced/wallets/react-wallet-v2/src/lib/smart-accounts/builders/EncodeLib.ts
- advanced/wallets/react-wallet-v2/src/lib/smart-accounts/builders/SafeUserOpBuilder.ts
- advanced/wallets/react-wallet-v2/src/lib/smart-accounts/builders/SmartSessionUserOpBuilder.ts
- advanced/wallets/react-wallet-v2/src/lib/smart-accounts/builders/UserOpBuilder.ts
- advanced/wallets/react-wallet-v2/src/pages/api/sendUserOp.ts
- advanced/wallets/react-wallet-v2/yarn.lock
Implemented the sendUserOp service for SafeUserOpBuilder
> Feat: Enable sendUserOp for userOpBuilder service

- advanced/wallets/react-wallet-v2/src/pages/_middleware.ts
To resolve CORS error when calling the UserOpBuilder service endpoints
> add middleware for userOp builder service

- dapps/web3modal/react-solana/src/App.tsx
This PR adds a few more social login options and also shows how a user can enable or disable Onramp. 
Tested locally
> Solana example: Updating the example to showcase Solana v2 functionalities

- advanced/wallets/react-wallet-v2/src/data/EIP155Data.ts
remove duplicate chain declaration
> fix:duplicate chain declaration

- advanced/dapps/react-dapp-v2/src/components/OriginSimulationDropdown.tsx
- advanced/dapps/react-dapp-v2/src/contexts/ClientContext.tsx
Fixed verify simulation test cases - `valid`, `invalid` & `unknown`
> fix: verify simulations

- advanced/dapps/smart-sessions-demo/src/components/DcaComponents/AssetBalance.tsx
- advanced/dapps/smart-sessions-demo/src/components/DcaComponents/Dashboard.tsx
- advanced/dapps/smart-sessions-demo/src/schema/DCAFormSchema.ts
- advanced/dapps/smart-sessions-demo/src/utils/DCAUtils.ts
Adding refetch to the dashboard and second interval to the DCA form
> chore: refetch and second interval

- dapps/appkit-siwe/next/app/config/index.tsx
- dapps/appkit-siwe/next/app/page.tsx
- dapps/appkit-siwe/next/package.json
- dapps/appkit-siwe/react/package.json
- dapps/appkit-siwe/react/pnpm-lock.yaml
- dapps/appkit-siwe/react/server/package.json
- dapps/appkit-siwe/react/server/pnpm-lock.yaml
- dapps/appkit-siwe/react/server/server.js
- dapps/appkit-siwe/react/src/main.tsx
- dapps/appkit-siwe/react/src/utils/siweUtils.ts
+ fix react example to split the chainID to only get the Id
+ fix next example to return null when no session
+ upgrade both
> Fix: chainid siwe example

- dapps/appkit-siwe/next/app/api/auth/[...nextauth]/route.ts
- dapps/appkit-siwe/next/package.json
- dapps/appkit-siwe/next/pnpm-lock.yaml
- dapps/appkit-siwe/react/package.json
- dapps/appkit-siwe/react/pnpm-lock.yaml
- dapps/appkit-siwe/react/server/package.json
- dapps/appkit-siwe/react/server/pnpm-lock.yaml
- dapps/appkit-siwe/react/server/server.js
- dapps/appkit-siwe/react/src/utils/siweUtils.ts
- Fix React Example
- Fix next.js Example
- update to latest 1.6.4
> fix verifyMsg in SIWE

- advanced/dapps/chat-demo-agent/src/components/chat-components/ChatInterface.tsx
> chore: updated the text

- advanced/dapps/chain-abstraction-demo/app/hooks/useGiftDonut.tsx
- advanced/dapps/chain-abstraction-demo/app/layout.tsx
- advanced/dapps/chain-abstraction-demo/components/CheckWalletToast.tsx
- advanced/dapps/chain-abstraction-demo/components/TransactionToast.tsx
- advanced/dapps/chain-abstraction-demo/components/gift-donut-modal-views/CheckoutReceipentAddressView.tsx
- advanced/dapps/chain-abstraction-demo/config/index.tsx
- advanced/dapps/chain-abstraction-demo/package.json
- advanced/dapps/chain-abstraction-demo/pnpm-lock.yaml
- display toast with message "Check you wallet to approve transaction"
- display transaction completed toast with time taken
> Add loading on checkout

- advanced/dapps/chain-abstraction-demo/hooks/useWalletGetAssets.ts
- advanced/dapps/chain-abstraction-demo/package.json
- advanced/dapps/chain-abstraction-demo/types/ERC7811.ts
- advanced/dapps/chain-abstraction-demo/yarn.lock
Updated `wallet_getAssets` implementation to use CAIP-345 in donut app
> chore: update wallet_getAssets implementation to use CAIP-345 

- advanced/wallets/react-wallet-v2/src/data/EIP155Data.ts
- advanced/wallets/react-wallet-v2/src/views/SessionProposalModal.tsx
updating approvedNamespaces to include `wallet_checkout` only in eip155.
> fix: updating namespace to include wallet_checkout only in eip155

- advanced/wallets/react-wallet-v2/src/data/TonData.ts
- advanced/wallets/react-wallet-v2/src/lib/TonLib.ts
- Use TonCenter api while BAPI is in development
> feat: use toncenter
