reown-com/web-examples

wallets/react-wallet-v2/src/components/RelayRegionPicker.tsx
wallets/react-wallet-v2/src/data/RelayerRegions.ts
wallets/react-wallet-v2/src/hooks/useInitialization.ts
wallets/react-wallet-v2/src/pages/settings.tsx
wallets/react-wallet-v2/src/store/SettingsStore.ts
wallets/react-wallet-v2/src/utils/WalletConnectUtil.ts

Another PR related to #57, this PR is particularly for the `react-wallet-v2` app
[Loom Video](https://www.loom.com/share/aa4c756e71294fa99e4982d983addf01)
Process (Data)
1. Add `relayerRegionURL` + `setRelayerRegionURL` to settings store
2. Call `relayerRegionURL` through `valtio` through `useInitialization()`
3. Pass `relayerRegionURL` through to `createClient()`
4. Track the `prevRelayerURLValue` through `useRef`
5. Re-render when new `relayerURL` value is changed which instantiates a new `createClient()`
Process (Frontend)
1. Add types and utils list to `RelayerRegions` in the data folder
2. Create a `RelayRegionPicker` (Similar to AccountPicker) component.
3. SetState on the `select` value. Data should pass through

feat(relayer): Add relayer region to the wallet v2 settings

---

dapps/react-dapp-v2/package.json
dapps/react-dapp-v2/src/contexts/JsonRpcContext.tsx
dapps/react-dapp-v2/yarn.lock

Add custom verification for Celo transaction type when using `eth_signTransaction`. The Celo transaction type does not work with the existing validation method `EthTransaction.fromSerializedTx`.

fix: eth_signTransaction signer verification for Celo

---

wallets/react-wallet-v2/src/pages/session.tsx

When updating the session, the console returns an error because in the react-dapp-v2 the session namespace has all five methods and events included. To update a session, you can only add chains, everything else has to be the same.
- Updated the `newNs` object to be the same as example dapp
The dapp uses all of the `EIP155` methods:
[Constants](https://github.com/WalletConnect/web-examples/blob/main/dapps/react-dapp-v2/src/constants/default.ts#:~:text=DEFAULT_EIP155_METHODS)
[Namespace where the methods are all set](https://github.com/WalletConnect/web-examples/blob/main/dapps/react-dapp-v2/src/helpers/namespaces.ts#:~:text=methods%3A%20getSupportedMethodsByNamespace(namespace)%2C)

Update newNs object to match Dapps session namespace

---

wallets/react-web3wallet/src/data/EIP155Data.ts

Removed instance of `eth_sendRawTransaction` since it's not being used anywhere in the example wallet.

Remove 'eth_sendRawTransaction' from const list

---

dapps/react-dapp-v2/package.json
dapps/react-dapp-v2/src/chains/cosmos.ts
dapps/react-dapp-v2/src/chains/eip155.ts
dapps/react-dapp-v2/src/chains/elrond.ts
dapps/react-dapp-v2/src/chains/near.ts
dapps/react-dapp-v2/src/chains/polkadot.ts
dapps/react-dapp-v2/src/chains/solana.ts
dapps/react-dapp-v2/src/chains/tron.ts
dapps/react-dapp-v2/src/components/Blockchain.tsx
dapps/react-dapp-v2/src/contexts/ChainDataContext.tsx
dapps/react-dapp-v2/src/helpers/types.ts
dapps/react-dapp-v2/yarn.lock

- Context: https://walletconnect.slack.com/archives/C03RME3BS9L/p1677021657070509
- We've had some reports of some people seeing SSL errors when the dapp tries to resolve chain data via the `caip-api` pkg, which under the hood relies on the legacy `blockchain-api.xyz` as a data source.
- We still rely on a `blockchain-api.xyz` call to resolve some chain logos, but worst case scenario now is some broken logo assets if that domain can't be resolved, not a crashed dapp.
- Explicitly blocked this domain in network inspector to recreate the issue and this fixes the crashing behaviour.

fix(dapp): removes reliance on `caip-api` pkg for blockchain data

---

dapps/react-dapp-v2/src/contexts/JsonRpcContext.tsx
dapps/react-dapp-v2/src/helpers/api.ts

- Fixes #117 
- Supersedes #140 
- Tested that existing signature validation still works as expected with https://react-wallet.walletconnect.com, on top of the additional ERC/EIP 1271 validation now accounted for.

fix(dapp): makes sig validation compatible with ERC-1271

---

dapps/react-dapp-v2/src/contexts/JsonRpcContext.tsx
dapps/react-dapp-v2/src/helpers/utilities.ts

Updated `Solana` rpc provider to use `rpc.walletconnect.com` for mainnet

refactor: solana mainnet rpc url

---

wallets/react-wallet-v2/README.md
wallets/react-wallet-v2/src/components/AccountPicker.tsx
wallets/react-wallet-v2/src/components/Navigation.tsx

Minor changes 
The `data-testid` tags were placed in next/link elements
I did not expect this to be an issue, but it was
_next/link_ does not actually render `<Link>` as an element
It modifies the `<a>` tag inside of it with the href passed 
Which would remove the `data-testid` tags from the dom

fix: corrected e2e navigation tags

---

dapps/react-dapp-auth/package-lock.json
dapps/react-dapp-auth/package.json
dapps/react-dapp-v2-cosmos-provider/package.json
dapps/react-dapp-v2-cosmos-provider/yarn.lock
dapps/react-dapp-v2-with-ethers/package.json
dapps/react-dapp-v2-with-ethers/yarn.lock
dapps/react-dapp-v2-with-web3js/package.json
dapps/react-dapp-v2-with-web3js/yarn.lock
dapps/react-dapp-v2/package.json
dapps/react-dapp-v2/yarn.lock
wallets/react-wallet-auth/package-lock.json
wallets/react-wallet-auth/package.json
wallets/react-wallet-chat/package.json
wallets/react-wallet-chat/yarn.lock
wallets/react-wallet-v2/package.json
wallets/react-wallet-v2/yarn.lock

This reverts commit 00e866ebb4d7f92ec867ff0aa174115a07f25a88.
- https://github.com/vercel/next.js/issues/48593
- Looks like the build was fine on PR preview and then broke on main 🤔 
- Reverting until we coordinate a proper next.js@13 upgrade via renovateBot
- Fixes #308

Revert "fix(deps): update dependency next to v12.3.4 (#286)"

---

wallets/react-wallet-v2/src/views/SessionProposalModal.tsx

This PR is added because when trying to connect from dApps that use the WalletConnect  [Near Wallet Selector](https://github.com/near/wallet-selector) such as [GuestBook Example](https://near.github.io/wallet-selector/) the pairing is failing because of mismatch of events.
The proposal from near/wallet-selector by default adds the `accountsChanged` and `chainChanged` to the events array but looking at the [SessionProposalModal.tsx#L114](https://github.com/WalletConnect/web-examples/blob/main/wallets/react-wallet-v2/src/views/SessionProposalModal.tsx#L114) it assumes that the supported events should be an `[]` empty array.
This is resulting in [buildApprovedNamespaces](https://github.com/WalletConnect/web-examples/blob/main/wallets/react-wallet-v2/src/views/SessionProposalModal.tsx#L240) …

Add accountsChanged and chainChanged events for NEAR

---

dapps/react-dapp-v2/src/constants/default.ts
wallets/react-wallet-v2/src/components/ChainDataMini.tsx
wallets/react-wallet-v2/src/data/MultiversxData.ts
wallets/react-wallet-v2/src/data/chainsUtil.ts
wallets/react-wallet-v2/src/views/SessionProposalModal.tsx
wallets/react-wallet-v2/src/views/SessionSignMultiversxModal.tsx

Check for the whole chain identifier ( `namespace` + ":" + `reference` ) in `getChainData` instead of just reference(chainId) to avoid conflicts between chains that share the same reference ( `testnet` for NEAR Testnet and Tezos Testnet or `1` for Ethereum Mainnet and MultiversX Mainnet)
Updated the MultiversX namespace to the CAIP-2 compliant `mvx` used in the ecosystem

Check for the whole chain identifier ( namespace + ":" + reference )

---

dapps/react-dapp-v2/package.json
dapps/react-dapp-v2/yarn.lock

Update outdated `@celo/wallet-base` dependency (3.0.1 --> 5.1.1).
In the WalletConnect demo dApp, it's used for verifying the correctness of the `eth_signTransaction` result using Celo network wallet (e.g. [Valora wallet](https://valoraapp.com)).
The latest version of `@celo/wallet-base` supports transactions encoded in the [CIP-42](https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0042.md) format, which is becoming the recommended one in within the Celo network. The legacy Celo transaction types are still supported as well.

chore: update `@celo/wallet-base` dependency

---

advanced/wallets/react-wallet-v2/src/pages/walletconnect.tsx
advanced/wallets/react-wallet-v2/src/pages/wc.tsx

Added new page `/wc` that accepts deeplinks (`?uri=wc%3Ab2222ed98bec37db97d17028849eb3a3d0d5179cac4cfc036e6602d3e32bd87f%402%3Frelay-protocol%3Dirn%26symKey%3D3081499b0c00c3674b648f3d3262ae8aa689639166a0c5ba69f1cad24d171252`) to initialize connection instead of only copy/paste of qr

feat: wallet connection via deeplink

---

advanced/wallets/react-wallet-v2/src/hooks/useWalletConnectEventsManager.ts
advanced/wallets/react-wallet-v2/src/pages/sessions.tsx
advanced/wallets/react-wallet-v2/src/store/SettingsStore.ts
advanced/wallets/react-wallet-v2/src/views/SessionProposalModal.tsx

fix: implements dynamic session list

---

advanced/wallets/react-wallet-v2/src/components/Modal.tsx
advanced/wallets/react-wallet-v2/src/pages/walletconnect.tsx
advanced/wallets/react-wallet-v2/src/pages/wc.tsx
advanced/wallets/react-wallet-v2/src/store/ModalStore.ts
advanced/wallets/react-wallet-v2/src/views/LoadingModal.tsx
advanced/wallets/react-wallet-v2/src/views/SessionProposalModal.tsx

- added `Loading Modal` that can be triggered for any loading need
- added message after 15s in loader modal that request might be taking too long

feat: added `LoadingModal` 

---

advanced/wallets/react-wallet-v2/src/components/SmartAccountCard.tsx
advanced/wallets/react-wallet-v2/src/hooks/useSmartAccount.ts
advanced/wallets/react-wallet-v2/src/lib/SmartAccountLib.ts
advanced/wallets/react-wallet-v2/src/utils/EIP155RequestHandlerUtil.ts
advanced/wallets/react-wallet-v2/src/views/SessionProposalModal.tsx

Smart accounts were being incorrectly instanced by not providing the correct chain. 
- Extracted chain and account information from the namespace and added a couple of validations before appending smart accounts to the accounts entry of the session response.
- Minor fix on smart account client to allow to always have an address
- Minor change in SmartAccountCard  component to always show SA address.
- If multiple chains are provided during session request, only the first chain's smart account is being instanced. Need to look into it but think I can do in separate PR

fix: smart account creation on session requests

---

advanced/wallets/react-wallet-v2/src/components/ProjectInfoCard.tsx

Adding the `data-testid` attribute such that Playwright can properly assert on it.
Confirmed in preview link.

feat(ui-test): enable verify to be covered

---

advanced/wallets/react-wallet-v2/src/lib/SmartAccountLib.ts
advanced/wallets/react-wallet-v2/src/utils/HelperUtil.ts
advanced/wallets/react-wallet-v2/src/utils/SmartAccountUtils.ts
advanced/wallets/react-wallet-v2/src/views/SessionProposalModal.tsx

https://files.slack.com/files-pri/TB3H1FRHU-F06JGM2L94H/screenshot_2024-02-09_at_12.17.33___pm.png
Connection on wallet3inbox hanged on approval. 
Added error handling and validation to skip SA connection when there are none

hotfix for wallet3inbox connection

---

advanced/wallets/react-wallet-v2/src/views/SessionProposalModal.tsx

Filtered only allowed chains when connecting SA. If SA is available, make sure it is the one that gets displayed on the dApp you connect.

connect to a dApp with SA, create SA on building a crypto link

---

advanced/wallets/react-wallet-v2/src/hooks/usePriorityAccounts.ts
advanced/wallets/react-wallet-v2/src/views/SessionProposalModal.tsx

`buildApprovedNamespaces` throws when required namespaces are not supported by the wallet and must be catched to avoid unhandled exceptions

fix: catch namespace builder exception

---

advanced/wallets/react-wallet-v2/src/utils/WalletConnectUtil.ts

Enable trace logs for React Wallet so Playwright can easily access them for debugging test flakiness. [Slack conversation](https://walletconnect.slack.com/archives/C03RME3BS9L/p1711561028218789?thread_ts=1711559317.364129&cid=C03RME3BS9L)

chore: enable trace logs for react-wallet

---

advanced/wallets/react-wallet-v2/src/views/SessionProposalModal.tsx

fixed a bug where when smart accounts were enabled, they were replacing the available EOA on proposal approval

fix: session approval accounts order

---

advanced/dapps/react-dapp-v2/src/components/app/index.tsx
advanced/dapps/react-dapp-v2/src/pages/index.tsx
advanced/wallets/react-wallet-v2/src/utils/EIP5792WalletUtil.ts
advanced/wallets/react-wallet-v2/src/views/SessionProposalModal.tsx

on session approval, wallet capabilities data as defined for wallet_getCapabilities in EIP5792 is added to sessionProperties,
this gives another way for dapps to check wallet's capabilities without requesting via wallet_getCapabilities method.

 added CAIP-25 to remove the round-trip required for wallet_getCapabilities

---

advanced/dapps/react-dapp-v2/src/contexts/JsonRpcContext.tsx
advanced/dapps/react-dapp-v2/src/modals/RequestLoaderModal.tsx
advanced/dapps/react-dapp-v2/src/pages/index.tsx

Action wallet_getCapabilities will return cached data from session.sessioProperties if present else it will send a call to wallet to get the capabilities.
Added RequestLoaderModal.tsx for waiting for request to get fulfil from the wallet, this modal have different display message, RequestModal can be refactored to support both, but for simplicity created a separate modal to handle request which don't need a user action

Use cached wallet_getCapabilities

---

renovate.json

- Renovatebot is very trigger-happy with rebasing its PRs immediately when it falls behind the base branch, even if not conflicted.
- This is causing Vercel deployment floods unnecessarily and clogging up the deployment pipeline in other Vercel projects outside of our examples
- See: https://docs.renovatebot.com/updating-rebasing/
- Only rebase when conflicted. If that still doesn't help we can move to `rebaseWhen: "never"` for full manual control

chore(renovate): only rebase on conflict

---

advanced/wallets/react-wallet-v2/src/store/SettingsStore.ts
advanced/wallets/react-wallet-v2/src/utils/SmartAccountUtil.ts

This fix removes the requirement to reload the wallet after Smart account is enabled/toggled. Now the state is updated without reload.

fix wallet reload on smart account toggle

---

advanced/wallets/react-wallet-v2/src/consts/smartAccounts.ts
advanced/wallets/react-wallet-v2/src/data/EIP155Data.ts
advanced/wallets/react-wallet-v2/src/data/EIP5792Data.ts
advanced/wallets/react-wallet-v2/src/hooks/useSmartAccounts.ts
advanced/wallets/react-wallet-v2/src/lib/smart-accounts/KernelSmartAccountLib.ts
advanced/wallets/react-wallet-v2/src/lib/smart-accounts/SmartAccountLib.ts
advanced/wallets/react-wallet-v2/src/pages/settings.tsx
advanced/wallets/react-wallet-v2/src/store/SettingsStore.ts
advanced/wallets/react-wallet-v2/src/utils/EIP5792RequestHandlerUtils.ts
advanced/wallets/react-wallet-v2/src/utils/SmartAccountUtil.ts

1. Added switch for enabling local AA infra setup for sample wallet
The local AA infra can be run using this guide, it assumes default URLs for bundler,paymasters and publicRPC from this guide
https://docs.pimlico.io/permissionless/how-to/local-testing 
Closes RES-13

Enable local AA infra support on sample wallet

---

advanced/wallets/react-wallet-v2/src/lib/smart-accounts/SafeSmartAccountLib.ts
advanced/wallets/react-wallet-v2/src/lib/smart-accounts/SmartAccountLib.ts

Changed function argument to handle Hex data for `value` field on `SafeSmartAccountLib.ts` and `SmartAccountLib.ts`. 
`sendTransaction({ to, value, data }: { to: Address; value: bigint; data: Hex })` to
`sendTransaction({ to, value, data }: { to: Address; value: bigint | Hex; data: Hex })`

fix: sendTransaction arg type

---

.github/workflows/pr_checks.yml
.github/workflows/ui_tests.yml

- Ensure that the `ui_tests` workflow runs against W3M `main` (it was still pointed at the `V4` branch)
- Do not run PR checks on unrelated diffs (i.e. anything not modifying `react-wallet-v2` or `react-dapp-v2`)
- Not seen here: removed the style check and UI test jobs from being required in the repo settings so we don't hang on `Expected - Waiting for status to be reported`

fix(gha): run against ui_tests.yml@main, do not run on unrelated PR diffs

---

advanced/wallets/react-wallet-v2/src/hooks/useWalletConnectEventsManager.ts
advanced/wallets/react-wallet-v2/src/pages/sessions.tsx
advanced/wallets/react-wallet-v2/src/pages/wc.tsx

- added refresh sessions list util
- force refresh session list when `/sessions` route is loaded
This resolves a bug when initiating disconnect from the wallet was incorrectly showing the session as active in the session list

fix: refreshes session list when `/sessions` route is loaded

---

advanced/wallets/react-wallet-v2/src/pages/settings.tsx

text was incorrectly set to sign client but versioning points to web3wallet

fix: replces sign with web3wallet in text

---

advanced/wallets/react-wallet-v2/src/data/SolanaData.ts
advanced/wallets/react-wallet-v2/src/hooks/useWalletConnectEventsManager.ts
advanced/wallets/react-wallet-v2/src/lib/SolanaLib.ts
advanced/wallets/react-wallet-v2/src/utils/SolanaRequestHandlerUtil.ts

This PR is adding `signAndSendTransaction` for Solana wallet by listening to `solana_signAndSendTransaction` RPC call.
https://github.com/user-attachments/assets/243b1597-3f00-484a-b3b5-dc1aa827390d

feat: solana sign and send transaction

---

advanced/wallets/react-wallet-v2/package.json
advanced/wallets/react-wallet-v2/src/lib/SolanaLib.ts
advanced/wallets/react-wallet-v2/src/utils/SolanaRequestHandlerUtil.ts
advanced/wallets/react-wallet-v2/yarn.lock

This PR is updating the Solana's WalletConnectConnector RPC requests to use serialized transactions instead of object to communicate with wallets.
https://github.com/user-attachments/assets/7825c5aa-1317-47ed-be64-cfcf720a086f
This is related to https://github.com/WalletConnect/web3modal/pull/2677

refactor: solana wallet rpc interface

---

advanced/wallets/react-wallet-v2/src/lib/smart-accounts/builders/SafeUserOpBuilder.ts

Due to a timeout issue on Vercel when waiting for transaction receipt (maximum wait time is 15 seconds), we are now returning the `userOpHash` in the response for the `/sendUserOp` endpoint.
For retrieving the receipt or transaction hash, it is recommended that the app use the [Blockchain Bundler API](https://specs.walletconnect.com/2.0/specs/servers/blockchain/blockchain-bundler-api).

fix: return userOpHash instead of txHash

---

advanced/wallets/react-wallet-v2/src/utils/MultibridgeUtil.ts

We were both getting and executing transactions one by one. Changed the logic to return the list of transaction to be executed and wallet should just sign and broadcast them.

chore: extract chain abstraction transaction fetch logic

---

advanced/wallets/react-wallet-v2/src/views/SessionProposalModal.tsx

Added a query string `amountsToApproveEvm` to determine how many accounts can be connected.

chore: amount of addresses to approve (evm)

---

advanced/wallets/react-wallet-v2/src/views/SessionProposalModal.tsx

Fixed unhandled exception in session proposal modal when non `eip155` namespace was proposed

fix: adds conditional check if `eip155` exists in `namespaces` props

---

advanced/wallets/react-wallet-v2/src/lib/smart-accounts/SmartAccountLib.ts

fix bug with user op gas estimation during paymaster sponsored ops

chore: copy verification gas limit

---

advanced/wallets/react-wallet-v2/src/pages/wc.tsx
advanced/wallets/react-wallet-v2/src/store/ModalStore.ts

The wallet now closes automatically after responding to a request from a deeplink. This removes tab clutter as apps open the wallet in a new new tab on every request  
https://www.notion.so/walletconnect/Engineering-1405a07b0a424104b65d9df0c2e6648e?p=1a53a661771e8077bf2dc67e0f2020b2&pm=s

feat: close wallet tab after request modal is closed

---

advanced/dapps/chain-abstraction-demo/app/hooks/useGiftDonut.tsx
advanced/dapps/chain-abstraction-demo/data/EIP155Data.ts
advanced/dapps/chain-abstraction-demo/utils/BalanceFetcherUtil.ts

Removed magic number to use decimals added into the token structure this way the routes work for all tokens (in this case USDs has 18)
https://github.com/user-attachments/assets/860e66c9-3b12-432c-9de1-d17354fec023

fix: support decimals for tokens

---

advanced/wallets/react-wallet-v2/src/views/SessionGetBip122AddressesModal.tsx

also fixes wallet crash if addresses map is empty

fix: provides chainId to bip122.getAddresses

---

advanced/wallets/react-wallet-v2/package.json
advanced/wallets/react-wallet-v2/src/components/ModalFooter.tsx
advanced/wallets/react-wallet-v2/src/components/Navigation.tsx
advanced/wallets/react-wallet-v2/src/components/PairingCard.tsx
advanced/wallets/react-wallet-v2/src/components/SessionCard.tsx
advanced/wallets/react-wallet-v2/src/hooks/useInitialization.ts
advanced/wallets/react-wallet-v2/src/utils/WalletConnectUtil.ts
advanced/wallets/react-wallet-v2/yarn.lock

React wallet wasn't working in dev mode, this PR fixes the issues
- fixed `@walletconnect` deps to single version as`@reown/walletkit` & `@reown/appkit-experimental` both depend on different versions
- updated `@solana/web3.js` as the old one wasn't working properly
- updated `<Link>` usage around the wallet as it no longer supports nested `<a>` elements
- fixed double `onInitialize` call

fix: react wallet

---

advanced/wallets/react-wallet-v2/src/utils/WalletConnectUtil.ts

the logger was updated to `warn` in https://github.com/reown-com/web-examples/pull/880 which broke Appkit canary due to its reliance on trace logs

chore: sets wallet logger to trace

---

advanced/dapps/react-dapp-v2/package.json
advanced/dapps/react-dapp-v2/pnpm-lock.yaml
advanced/dapps/react-dapp-v2/src/contexts/ClientContext.tsx
advanced/dapps/react-dapp-v2/src/contexts/JsonRpcContext.tsx
advanced/dapps/react-dapp-v2/src/helpers/namespaces.ts
advanced/dapps/react-dapp-v2/src/helpers/utilities.ts

This PR updates `react-app` by replacing the deprecated `wcm` with `appkit`, also I've updated typescript & eslint

refactor: replaces WCM with Appkit

---

advanced/dapps/react-dapp-v2/src/contexts/JsonRpcContext.tsx
advanced/dapps/react-dapp-v2/src/helpers/sui.ts
advanced/dapps/react-dapp-v2/src/pages/index.tsx
advanced/wallets/react-wallet-v2/src/lib/SuiLib.ts
advanced/wallets/react-wallet-v2/src/views/SessionSignAndExecuteSuiTransactionModal.tsx
advanced/wallets/react-wallet-v2/src/views/SessionSignSuiTransactionModal.tsx

Refactored the transaction payload of `sui_signTransaction` and `sui_signAndExecuteTransaction` to be base64 encoded BCS instead of JSON

refactor: sui transactions

---

advanced/dapps/react-dapp-v2/package.json
advanced/dapps/react-dapp-v2/pnpm-lock.yaml
advanced/wallets/react-wallet-v2/package.json
advanced/wallets/react-wallet-v2/yarn.lock

This PR updates various @walletconnect/ packages from version 2.21.3 to 2.21.8 across the React wallet and dapp applications to ensure consistency and incorporate the latest features and bug fixes.
- Updates all @walletconnect/ package versions from 2.21.3 to 2.21.8
- Updates @reown/walletkit from 1.2.7 to 1.2.10 in the wallet application
- Ensures version consistency across both resolutions and overrides sections

chore: updates `@walletconnect/` packages to `2.21.8`

---

advanced/wallets/react-wallet-v2/src/lib/TonLib.ts

- Shows un-bounceable address in TON
- Uses payload in `sendMessage` when available

chore: show unbounceable address, use payload if available
